[versions]
hikaricp = "6.3.0"
jshepherd = "3.3.1"
bukkit-v1165 = "1.16.5-R0.1-SNAPSHOT"

[libraries]
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
jshepherd = { group = "com.github.bsommerfeld.jshepherd", name = "core", version.ref = "jshepherd"}
jshepherd-yaml = { group = "com.github.bsommerfeld.jshepherd", name = "yaml", version.ref = "jshepherd"}
bukkit-v1165 = { group = "org.spigotmc", name = "spigot-api", version.ref = "bukkit-v1165" }

[bundles]
jshepherd-yaml = ["jshepherd", "jshepherd-yaml"]